# Forked from https://github.com/withastro/automation/blob/main/.github/workflows/format.yml

name: Format
on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    format:
        if: github.repository_owner == 'MoustaphaDev'
        runs-on: ubuntu-latest
        env:
            NODE_OPTIONS: '--max_old_space_size=4096'
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
                  # Needs access to push to main
                  token: ${{ secrets.GH_TOKEN }}

            - name: Setup PNPM
              uses: pnpm/action-setup@v2

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Format code
              run: pnpm run format

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: '[ci] format'
                  branch: ${{ github.head_ref }}
                  commit_user_name: ${{ github.actor }}
                  commit_user_email: ${{ github.actor }}@users.noreply.github.com
                  commit_author: ${{ github.event.commits[0].author.name }} <${{ github.actor }}@users.noreply.github.com>
